### ISSUE TITLE
Allow many-to-many connections

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#15]
When adding many-to-many connections, for example in pooled_from attribute in biosample, it should allow multiple items to be added.

Example -
http://target.wustl.edu:8006/api/biosamples/TRGTSMP00010780

Observed -
screen shot 2017-11-17 at 8 47 26 am

Expected -
screen shot 2017-11-17 at 8 44 46 am

Xiaoyu: The main issue is solved, but it would be better if we can removed the empty string in list. For example, "biosample": [] instead of "biosample": [""]

In particular, biosample pooled_from other biosamples, link mouse to multiple bioprojects.

**Comment by debugpoint136** [comment]
- Applied a new fix to DEV1 using CYPHER..!
- Multiple connections should be possible on webUI and through API.
- Change introduced - the `connectionAcsn` should be an `Array` only. Even if only one relationship is being added.
@xzhuo testing the API part.
Needs to be deployed to PROD.

Still need to take care of remove connection part.

**Comment by xzhuo** [comment]
passed multiple connection function test using submission/populate pipeline.

**Comment by debugpoint136** [comment]
Pushed to PROD

**Comment by debugpoint136** [comment]
TODO: Need to address removing `multiple connections`

**Comment by xzhuo** [comment]
Can we close it?
Since there is a separated issue about remove multiple connections( #40 ) ?

**Comment by epehrsson** [comment]
@debugpoint136 , thoughts? I am ok with it, unless it is only deployed in one object; then should it be extended to all objects?

**Comment by epehrsson** [comment]
@debugpoint136 , close this out?

**Comment by debugpoint136** [comment]
closing it
