### ISSUE TITLE
Move sftp instructions

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#29]
The sftp submission instructions (https://submit.target.wustl.edu/sftp) are difficult to find except from the experiment dashboard. Solution: move to a more obvious/easily accessible location.

**Comment by epehrsson** [comment]
Some labs have created fake submissions to access the password, but we want to make sure they have created a submission before uploading data. Close?

**Comment by debugpoint136** [comment]
While this is not relevant anymore, there is a tangential issue of one password for everyone, and people misusing it download data by other labs. Daofeng had suggested making individual accounts/passwords for each lab. 
Let's create a new item and track it on trello. Closing this.
