### ISSUE TITLE
Implement excluded file flag

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#31]
Groups would like to be able to submit data for testing purposes without having it excluded in official releases. Include a flag in the submission dashboard that would allow users to identify files that are for testing only.

**Comment by epehrsson** [comment]
I added a "pilot" field to file.js, but it should be added to the submission dashboard too

**Comment by epehrsson** [comment]
@debugpoint136 , add pilot flag to submission dashboard please!

**Comment by epehrsson** [comment]
Added to the dashboard - can we close out?

**Comment by debugpoint136** [comment]
completed
