### ISSUE TITLE
Add records/user download

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#32]
Add button to submission dashboard allowing users to simultaneously download all metadata records they have ever submitted into one Excel file (implementing cypher query designed by Xiaoyu).

**Comment by epehrsson** [comment]
This is already implemented - has it been tested?

**Comment by epehrsson** [comment]
Can we close out? What testing needs to be done?

**Comment by epehrsson** [comment]
@debugpoint136 , I think it is finished!

**Comment by epehrsson** [comment]
Is this finished?

**Comment by debugpoint136** [comment]
@xzhuo can you please test and confirm?
