### ISSUE TITLE
Cannot save submission update log

### ISSUE THREAD

**Issue by xzhuo** [target2/SubmissionSystem#38]
1. The error message:
{'message': {'message': 'document must have an _id before saving',
             'name': 'MongooseError'},
 'statusCode': 503}

2. on my submission dashboard, none of my metadata submission has date. Is that by design or bug?

**Comment by debugpoint136** [comment]
@xzhuo  how to reproduce point 1. ?

I can reproduce point 2. Don't know what is the cause. Need to troubleshoot more.

**Comment by xzhuo** [comment]
I got it when I use the --update option

**Comment by xzhuo** [comment]
Fixed now, I am closing it.
