### ISSUE TITLE
Remove TGTFF0001 - TGTFF00012 metadata entries

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#39]
These are duplicate metadata entries generated by the Aylor group during system testing. We received permission from Thomas Konneker via Slack to remove them.

**Comment by epehrsson** [comment]
And TRGTASY0001

**Comment by kneeker** [comment]
This is Thomas Konneker.  I have requested the removal TGTFF0001 - TGTFF00012, TRGTASY0001, TRGTLIB0001, TRGTSMP0001, TRGTMSE0001, TRGTLTR0001, TRGTBPR0001, TRGTEXP0001

**Comment by xzhuo** [comment]
all of them deleted.

**Comment by xzhuo** [comment]
close?
