### ISSUE TITLE
Make non-required metadata field columns white

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#42]
As per Bo's request.

**Comment by xzhuo** [comment]
How about bold header for required fields?

**Comment by epehrsson** [comment]
We could do that - then just have two colors?

**Comment by xzhuo** [comment]
I changed the excel template. required column headers are bold, not required headers are italic.

**Comment by epehrsson** [comment]
Thanks! Are the instructions updated?

**Comment by xzhuo** [comment]
Yes. Please download a new template from website and make sure it is correct.

**Comment by epehrsson** [comment]
Template looks the same as before, is it manually linked?

**Comment by xzhuo** [comment]
Can you try "download all my metadata" ? I think we need to ask deepak to "refresh" the template file.

**Comment by epehrsson** [comment]
Suggestion by Data Wranglers: Update the Excel instructions to clarify that required fields are bold, non-required fields are italic.

**Comment by epehrsson** [comment]
Additionally, make separate colors for required/non-required relationships.

**Comment by epehrsson** [comment]
Suggestion by Metadata WG: Maybe 2-4 completely different colors

**Comment by epehrsson** [comment]
Suggestion: separate color for required/non-required metadata. Then, close issue?

**Comment by xzhuo** [comment]
I will change the relationship color and close it once done.

**Comment by epehrsson** [comment]
Finished?

**Comment by debugpoint136** [comment]
@xzhuo ?
