### ISSUE TITLE
Add md5sum check to data submission 

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#43]
Files uploaded as part of a submission should be checked against the registered md5sums, and the pipeline should not proceed without matching the number and md5sum of the registered files. Ideally, the user will be able to see if they do not match.

**Comment by epehrsson** [comment]
For all old submissions, we should check the actual md5sum of the file against the one listed by the user (md5sum.json) to confirm they are correct.

**Comment by epehrsson** [comment]
Completed, including check of old files?

**Comment by debugpoint136** [comment]
completed
