### ISSUE TITLE
Reject registered files with wrong extension

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#44]
Submitted files with the wrong extension will not be processed by the automated QC pipeline. The user should be informed that the files have the incorrect extension at the submission registration stage rather than after file upload.

**Comment by epehrsson** [comment]
@debugpoint136 , I forgot this important step. It should be implemented along with Issue #43 as part of automating the submission system.

**Comment by debugpoint136** [comment]
Good point! thanks!

**Comment by epehrsson** [comment]
Completed?

**Comment by debugpoint136** [comment]
Completed
