### ISSUE TITLE
Change format of Metadata Registry banner

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#47]
Thomas Konneker: "On the Metadata registry page, "Files" and "Experiments" are clickable, which is next "Other Metadata" which acts like the title of a folder.  It took me awhile the other day to realize that I wanted to click on Files because of that mixture."

**Comment by epehrsson** [comment]
Should we remove Experiments altogether from the Metadata Registry?

**Comment by debugpoint136** [comment]
Not sure if this is relevant anymore. It's unclear what needs to be fixed

**Comment by xzhuo** [comment]
I think he wants the "file" group with other metadata instead of stand alone. I don't know...
