### ISSUE TITLE
Timeout error during metadata submission

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#50]

**Comment by epehrsson** [comment]
@xzhuo , can you provide details?

**Comment by xzhuo** [comment]
I increased timeout to 60 secs. Seems working for Mutlu lab. Further improvement requires refactoring all the post requests.

**Comment by epehrsson** [comment]
Ok to close then?

**Comment by xzhuo** [comment]
yes. further change would be a new enhancement.
