### ISSUE TITLE
Cypher queries to update Data Phase and Submission ID

### ISSUE THREAD

**Issue by epehrsson** [target2/SubmissionSystem#59]
File: Data Phase and File: Submission ID are required but were added later and are not filled out for all submissions. We should use cypher queries to add this information for all files.

**Comment by epehrsson** [comment]
Is this finished?

**Comment by debugpoint136** [comment]
Can you take a look at this @xzhuo ? All the submissions have Data Phase on tracker database. Can be accessed at 
`https://5dum6c4ytb.execute-api.us-east-1.amazonaws.com/dev/submissions`
